// AUTO-GENERATED by sim/build_logo_arrays.py. Do not edit by hand.
#pragma once

#include <lvgl.h>

namespace logos_data {

// Returns a pointer to an embedded ARGB8888 logo for `symbol`
// (already uppercase, e.g. "AAPL"), or nullptr if not bundled.
const lv_image_dsc_t* find(const char* symbol);

}  // namespace logos_data
