"""Convert data/logos/*.png into a single C source file with embedded
lv_image_dsc_t entries (ARGB8888). The output goes to
src/ui/logos_data.cpp/.h and is compiled into both the firmware and the
sim, so logo rendering works identically without the LVGL FS / lodepng
path.

Run from the project root: python sim/build_logo_arrays.py
"""

import os
import sys
from PIL import Image

SRC = "data/logos"
OUT_DIR = "src/ui"
OUT_C   = os.path.join(OUT_DIR, "logos_data.cpp")
OUT_H   = os.path.join(OUT_DIR, "logos_data.h")

def emit_array(out, var, data: bytes):
    out.write(f"static const LV_ATTRIBUTE_LARGE_CONST uint8_t {var}[] = {{\n  ")
    for i, b in enumerate(data):
        out.write(f"0x{b:02x},")
        if (i + 1) % 16 == 0:
            out.write("\n  ")
        else:
            out.write(" ")
    out.write("\n};\n\n")

def main():
    pngs = sorted(f for f in os.listdir(SRC) if f.lower().endswith(".png"))
    if not pngs:
        print("no PNGs found in data/logos/", file=sys.stderr)
        sys.exit(1)

    entries = []
    with open(OUT_C, "w", encoding="utf-8") as out:
        out.write('// AUTO-GENERATED by sim/build_logo_arrays.py. Do not edit by hand.\n')
        out.write('#include "logos_data.h"\n\n')
        out.write('#include <cstring>\n\n')
        out.write('#ifndef LV_ATTRIBUTE_LARGE_CONST\n#define LV_ATTRIBUTE_LARGE_CONST\n#endif\n\n')

        for fname in pngs:
            sym  = os.path.splitext(fname)[0].upper()
            cvar = "logo_" + sym.replace("-", "_").replace(".", "_")
            img  = Image.open(os.path.join(SRC, fname)).convert("RGBA")
            w, h = img.size
            # LVGL ARGB8888 byte order: B, G, R, A (little-endian uint32).
            pixels = bytearray(w * h * 4)
            for i, (r, g, b, a) in enumerate(img.getdata()):
                pixels[i*4+0] = b
                pixels[i*4+1] = g
                pixels[i*4+2] = r
                pixels[i*4+3] = a
            emit_array(out, cvar + "_data", pixels)
            out.write(f'const lv_image_dsc_t {cvar} = {{\n')
            out.write(f'  .header = {{ .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_ARGB8888, '
                      f'.flags = 0, .w = {w}, .h = {h}, .stride = {w*4}, .reserved_2 = 0 }},\n')
            out.write(f'  .data_size = sizeof({cvar}_data),\n')
            out.write(f'  .data = {cvar}_data,\n')
            out.write(f'  .reserved = nullptr,\n')
            out.write('};\n\n')
            entries.append((sym, cvar))

        out.write('namespace logos_data {\n\n')
        out.write('const lv_image_dsc_t* find(const char* symbol) {\n')
        out.write('  if (!symbol) return nullptr;\n')
        for sym, cvar in entries:
            out.write(f'  if (std::strcmp(symbol, "{sym}") == 0) return &{cvar};\n')
        out.write('  return nullptr;\n')
        out.write('}\n\n')
        out.write('}  // namespace logos_data\n')

    with open(OUT_H, "w", encoding="utf-8") as out:
        out.write('// AUTO-GENERATED by sim/build_logo_arrays.py. Do not edit by hand.\n')
        out.write('#pragma once\n\n')
        out.write('#include <lvgl.h>\n\n')
        out.write('namespace logos_data {\n\n')
        out.write('// Returns a pointer to an embedded ARGB8888 logo for `symbol`\n')
        out.write('// (already uppercase, e.g. "AAPL"), or nullptr if not bundled.\n')
        out.write('const lv_image_dsc_t* find(const char* symbol);\n\n')
        out.write('}  // namespace logos_data\n')

    print(f"wrote {OUT_C} and {OUT_H} ({len(entries)} logos)")

if __name__ == "__main__":
    main()
